### ISSUE TITLE
Qiita Advent Calendar 2023 DMM Webcampのカレンダーについて

### ISSUE THREAD

**Issue by Keichan15** [take12012/take12012#1]
突然のIssue失礼致します。

DMM Webcamp Advent Calendar 2023の担当をさせて頂いているKeichan_15と申します。

この度、Qiita Advent Calendar 2023 DMM Webcampのカレンダーにつきまして、take12012様が18日目に記事投稿のご予約をされているかと存じます。

こちらについて、take12012様がこちらで確認している各日程のカレンダーアサイン者との整合性が取れず、身元を確認させて頂きたいご状況です。

本件、お手数ではございますがご確認頂けましたらご連絡頂けますでしょうか。
こちらのIssueもしくは下記メールアドレス宛にご連絡頂けますと幸いでございます。
keisuke1515gaming@outlook.jp

お忙しいところ恐れ入りますが、何卒ご確認よろしくお願い申し上げます。

**Comment by take12012** [comment]
Keichan_15様

こちらのアドカレは参加者が既に決まっているものだったのですね。
DMMが今年はQiitaのものなかったので代わりにWebcampに参加しようと思い、登録してしまいました。
削除させていただきます。申し訳ございません。

**Comment by Keichan15** [comment]
> Keichan_15様
> 
> 
> 
> こちらのアドカレは参加者が既に決まっているものだったのですね。
> 
> DMMが今年はQiitaのものなかったので代わりにWebcampに参加しようと思い、登録してしまいました。
> 
> 削除させていただきます。申し訳ございません。

こちらこそ、ご説明及ばず大変申し訳ございません。

またご機会ございましたら、その際は何卒よろしくお願い申し上げます。
